_target_: lsr.models.DualSparseEncoder
query_encoder:
  _target_: lsr.models.TransformerMLPSparseEncoder
  config:
    _target_: lsr.models.TransformerMLPConfig
    tf_base_model_name_or_dir: distilbert-base-uncased
    activation: softplus 
    norm: log1p
doc_encoder:
  _target_: lsr.models.TransformerMLMSparseEncoder
  config:
    _target_: lsr.models.TransformerMLMConfig
    tf_base_model_name_or_dir: distilbert-base-uncased
    activation: softplus
    norm: log1p 
    term_importance: epic 
    doc_quality: epic    
  