_target_: lexdistill.lsr.models.DualSparseEncoder
query_encoder:
  _target_: lexdistill.lsr.models.TransformerMLMSparseEncoder
doc_encoder:
  _target_: lexdistill.lsr.models.TransformerMLMSparseEncoder