_target_: lexdistill.lsr.models.DualSparseEncoder
query_encoder:
  _target_: lexdistill.lsr.models.TransformerMLMSparseEncoder
config:
  _target_: lexdistill.lsr.models.DualSparseConfig
  shared: True